version: '3'

services:
  app:
    build: .
    container_name: pyUploader
    entrypoint: /bin/bash -c "python app.py"
    ports:
      - 5055:5000
    restart: always
    volumes:
      - .:/code
    privileged: true